# Dockerfile.backend
FROM maven:3.8-openjdk-17-slim AS build

WORKDIR /app

# Копируем корневой pom.xml
COPY pom.xml .

# Копируем модуль backend
COPY backend backend/
COPY frontend/pom.xml ./frontend/
# Собираем только бэкенд
RUN mvn clean package -pl backend -am

# Финальный образ
FROM eclipse-temurin:17-jre-alpine

WORKDIR /app

COPY --from=build /app/backend/target/*.jar app.jar

ENV SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres?ApplicationName=account%20service
ENV SPRING_DATASOURCE_USERNAME=postgres
ENV SPRING_DATASOURCE_PASSWORD=postgres

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]
