FROM node:16-alpine AS build

WORKDIR /app

# Копируем файлы зависимостей
COPY frontend/package*.json ./

RUN npm cache clean --force
RUN npm install --legacy-peer-deps

# Копируем исходный код
COPY frontend/ ./

# Сборка приложения
RUN npm run build

# Второй этап - настройка Nginx
FROM nginx:alpine

# Копируем собранное приложение из предыдущего этапа
COPY --from=build /app/build /usr/share/nginx/html

# Копируем конфигурацию Nginx
COPY frontend/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 3000

CMD ["nginx", "-g", "daemon off;"]

