apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: __NAMESPACE__
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
      - name: __REGISTRY_SECRET__
      containers:
      - name: frontend
        image: __IMAGE_NAME__Frontend
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_API_URL
          value: http://jcat-backend-service:80  
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
