apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-myapp
  namespace: __NAMESPACE__
spec:
  storageClassName: local
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/db/postgres-myapp
  nodeAffinity:  
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node2

     
  
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc-myapp
  namespace: __NAMESPACE__
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
