apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-myapp
  namespace: __NAMESPACE__
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/db/postgres-myapp
     
  
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc-myapp
  namespace: __NAMESPACE__
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
